// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.30;

import {LPOracle} from 'contracts/LPOracle.sol';
import {Test} from 'forge-std/Test.sol';
import {ILPOracle} from 'interfaces/ILPOracle.sol';
import {IPriceGuard} from 'interfaces/IPriceGuard.sol';
import {IUniswapV2Pair} from 'interfaces/IUniswapV2Pair.sol';

contract UnitLPOracle is Test {
  function test_FairLPPrice_WhenFeedsAreConfiguredAndTheFairPriceIsWithinTheAllowedTWAPDeviation() external {
    vm.mockCall(
      _feed0,
      abi.encodeWithSignature('latestRoundData()'),
      abi.encode(uint80(1), int256(1e8), uint256(0), uint256(block.timestamp), uint80(1))
    );
    vm.mockCall(_feed0, abi.encodeWithSignature('decimals()'), abi.encode(uint8(8)));

    vm.mockCall(
      _feed1,
      abi.encodeWithSignature('latestRoundData()'),
      abi.encode(uint80(1), int256(2e8), uint256(0), uint256(block.timestamp), uint80(1))
    );
    vm.mockCall(_feed1, abi.encodeWithSignature('decimals()'), abi.encode(uint8(8)));

    uint256 _price = _lpOracle.fairLPPrice(address(_pair));

    uint256 _expected = (2 * sqrt(2000e18 * 8000e18) * sqrt(1e18 * 2e18)) / 4000e18;
    assertEq(_price, _expected);
  }

  function test_FairLPPrice_WhenARequiredFeedIsMissing() external {
    MockPair _otherPair = new MockPair();

    vm.expectRevert(LPOracle.LPOracle_FeedNotSet.selector);
    _lpOracle.fairLPPrice(address(_otherPair));
  }

  function test_FairLPPrice_WhenTotalSupplyIsZero() external {
    _pair.setTotalSupply(0);

    vm.expectRevert(LPOracle.LPOracle_InvalidTotalSupply.selector);
    _lpOracle.fairLPPrice(address(_pair));
  }

  function test_FairLPPrice_WhenAFeedAnswerIsNon_positive() external {
    vm.mockCall(
      _feed0,
      abi.encodeWithSignature('latestRoundData()'),
      abi.encode(uint80(1), int256(0), uint256(0), uint256(block.timestamp), uint80(1))
    );

    vm.expectRevert(LPOracle.LPOracle_InvalidFeedAnswer.selector);
    _lpOracle.fairLPPrice(address(_pair));
  }

  function test_FairLPPrice_WhenThePriceGuardRejectsThePrice() external {
    vm.mockCall(
      _feed0,
      abi.encodeWithSignature('latestRoundData()'),
      abi.encode(uint80(1), int256(1e8), uint256(0), uint256(block.timestamp), uint80(1))
    );
    vm.mockCall(_feed0, abi.encodeWithSignature('decimals()'), abi.encode(uint8(8)));

    vm.mockCall(
      _feed1,
      abi.encodeWithSignature('latestRoundData()'),
      abi.encode(uint80(1), int256(1e8), uint256(0), uint256(block.timestamp), uint80(1))
    );
    vm.mockCall(_feed1, abi.encodeWithSignature('decimals()'), abi.encode(uint8(8)));

    _priceGuard.setShouldRevert(true);

    vm.expectRevert(ILPOracle.LPOracle_StalePrice.selector);
    _lpOracle.fairLPPrice(address(_pair));
  }

  function test_SetFeeds_WhenCalledByTheOwner() external {
    address _newFeed0 = makeAddr('newFeed0');
    address _newFeed1 = makeAddr('newFeed1');

    vm.prank(_governance);
    _lpOracle.setFeeds(address(_pair), _newFeed0, _newFeed1);

    assertEq(_lpOracle.feed0(address(_pair)), _newFeed0);
    assertEq(_lpOracle.feed1(address(_pair)), _newFeed1);
  }

  function test_SetFeeds_WhenCalledByANon_owner(address _caller) external {
    vm.assume(_caller != _governance);
    vm.prank(_caller);
    vm.expectRevert();
    _lpOracle.setFeeds(address(_pair), makeAddr('newFeed0'), makeAddr('newFeed1'));
  }

  function test_SetPriceGuard_WhenCalledByTheOwner() external {
    MockPriceGuard _newPriceGuard = new MockPriceGuard();

    vm.prank(_governance);
    _lpOracle.setPriceGuard(_newPriceGuard);

    assertEq(address(_lpOracle.priceGuard()), address(_newPriceGuard));
  }

  function test_SetPriceGuard_WhenCalledByANon_owner(address _caller) external {
    vm.assume(_caller != _governance);
    MockPriceGuard _newPriceGuard = new MockPriceGuard();

    vm.prank(_caller);
    vm.expectRevert();
    _lpOracle.setPriceGuard(_newPriceGuard);
  }

  // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  // ==================== BULLOAK AUTOGENERATED SEPARATOR ====================
  // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  //    Code below this section could not be automatically moved by bulloak
  // =========================================================================

  // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  // ==================== BULLOAK AUTOGENERATED SEPARATOR ====================
  // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  //    Code below this section could not be automatically moved by bulloak
  // =========================================================================
  address internal _governance = makeAddr('governance');
  MockPair internal _pair;
  MockPriceGuard internal _priceGuard;
  LPOracle internal _lpOracle;

  address internal _feed0 = makeAddr('feed0');
  address internal _feed1 = makeAddr('feed1');

  function setUp() external {
    _pair = new MockPair();
    _pair.setReserves(2000e18, 8000e18);
    _pair.setTotalSupply(4000e18);

    _priceGuard = new MockPriceGuard();

    vm.prank(_governance);
    _lpOracle = new LPOracle(_governance, _priceGuard);

    vm.prank(_governance);
    _lpOracle.setFeeds(address(_pair), _feed0, _feed1);
  }

  function testFuzz_FairLPPrice_WhenReservesScaleTogether(
    uint112 _reserve0,
    uint112 _reserve1,
    uint96 _scale
  ) external {
    vm.assume(_reserve0 >= 1e6);
    vm.assume(_reserve1 >= 1e6);
    vm.assume(_scale > 0);
    vm.assume(uint256(_reserve0) * uint256(_scale) <= type(uint112).max);
    vm.assume(uint256(_reserve1) * uint256(_scale) <= type(uint112).max);

    vm.mockCall(
      _feed0,
      abi.encodeWithSignature('latestRoundData()'),
      abi.encode(uint80(1), int256(1e8), uint256(0), uint256(block.timestamp), uint80(1))
    );
    vm.mockCall(_feed0, abi.encodeWithSignature('decimals()'), abi.encode(uint8(8)));

    vm.mockCall(
      _feed1,
      abi.encodeWithSignature('latestRoundData()'),
      abi.encode(uint80(1), int256(1e8), uint256(0), uint256(block.timestamp), uint80(1))
    );
    vm.mockCall(_feed1, abi.encodeWithSignature('decimals()'), abi.encode(uint8(8)));

    _pair.setReserves(_reserve0, _reserve1);
    _pair.setTotalSupply(1e18);
    uint256 _basePrice = _lpOracle.fairLPPrice(address(_pair));

    _pair.setReserves(uint112(uint256(_reserve0) * uint256(_scale)), uint112(uint256(_reserve1) * uint256(_scale)));
    _pair.setTotalSupply(uint256(_scale) * 1e18);
    uint256 _scaledPrice = _lpOracle.fairLPPrice(address(_pair));

    assertApproxEqRel(_scaledPrice, _basePrice, 1e14);
  }

  function sqrt(uint256 _x) internal pure returns (uint256 _result) {
    if (_x == 0) {
      return 0;
    }

    uint256 _z = (_x + 1) / 2;
    _result = _x;
    while (_z < _result) {
      _result = _z;
      _z = (_x / _z + _z) / 2;
    }
  }
}

contract MockPriceGuard is IPriceGuard {
  mapping(address _lpToken => address _adapter) public override twapAdapters;
  uint256 public immutable override maxDeviation = 0.05e18;
  bool internal _shouldRevert;

  function setShouldRevert(bool _value) external {
    _shouldRevert = _value;
  }

  function isValid(address, uint256) external view returns (bool _valid) {
    _valid = !_shouldRevert;
  }

  function checkPrice(address, uint256) external view {
    if (_shouldRevert) {
      revert PriceGuard_DeviationTooHigh();
    }
  }

  function setTwapAdapter(address _lpToken, address _adapter) external {
    twapAdapters[_lpToken] = _adapter;
  }
}

  contract MockPair is IUniswapV2Pair {
    uint112 internal _reserve0;
    uint112 internal _reserve1;
    uint32 internal _timestampLast;
    uint256 internal _totalSupply;

    function setReserves(uint112 _reserve0Value, uint112 _reserve1Value) external {
      _reserve0 = _reserve0Value;
      _reserve1 = _reserve1Value;
    }

    function setTotalSupply(uint256 _totalSupplyValue) external {
      _totalSupply = _totalSupplyValue;
    }

    function getReserves()
      external
      view
      returns (uint112 _reserve0Value, uint112 _reserve1Value, uint32 _timestampValue)
    {
      return (_reserve0, _reserve1, _timestampLast);
    }

    function token0() external pure returns (address _token0Value) {
      return address(0xA0);
    }

    function token1() external pure returns (address _token1Value) {
      return address(0xB0);
    }

    function totalSupply() external view returns (uint256 _totalSupplyValue) {
      return _totalSupply;
    }

    function price0CumulativeLast() external pure returns (uint256 _price0CumulativeLastValue) {
      return 0;
    }

    function price1CumulativeLast() external pure returns (uint256 _price1CumulativeLastValue) {
      return 0;
    }
  }
